name: vint_deployment
channels:
- pytorch
- conda-forge
dependencies:
- python=3.8.5
- cudatoolkit=11.0
- torchvision
- numpy
- matplotlib
# - pyyaml
- rospkg
- torch
- efficientnet_pytorch
- warmup_scheduler
- diffusers==0.11.1
