name: robodhruv_nomad
channels:
- defaults
- pytorch
dependencies:
- python=3.8.5
- cudatoolkit=10.
- numpy
- matplotlib
- ipykernel
- pip
- pip:
  - torch
  - torchvision
  - tqdm==4.64.0
  - git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git
  - git+https://github.com/real-stanford/diffusion_policy.git
  - opencv-python==4.1.2.30 # https://github.com/robodhruv/visualnav-transformer/issues/27
  - h5py==3.6.0
  - wandb==0.12.18
  - --extra-index-url https://rospypi.github.io/simple/ 
  - roslz4
  - prettytable
  - efficientnet-pytorch
  - warmup-scheduler
  - diffusers==0.11.1
  - lmdb 
  - vit-pytorch
  - positional-encodings
  - huggingface_hub==0.23.5 # https://stackoverflow.com/questions/78787623/cannot-import-name-datasetfilter-from-huggingface-hub



  


